### ISSUE TITLE
reddit config file

### ISSUE THREAD

**Issue by mustafademiray** [ngomez22/bot#3]
hello there, thank you for the share but i cant create any config file for redditConfig variable. as i see from the previous commits u never uploaded any redditconfig file. can you share an example for that redditConfig file ? 

thanks.

**Comment by ngomez22** [comment]
Hello,
The redditConfig file you're talking about has the following format:
``` javascript
module.exports = {
    // Unique string identifying the app
    userAgent: 'node:bot:v1 (by /u/username)',
    // It's possible to adjust throttle less than 1 request per second.
    // Snoocore will honor rate limits if reached.
    throttle: 300,
    oauth: {
        type: 'script',
        key: 'yourkey',
        secret: 'yoursecret',
        username: 'yourusername',
        password: 'yourpassword',
        // The OAuth scopes that we need to make the calls that we
        // want. The reddit documentation will specify which scope
        // is needed for evey call
        scope: ['identity', 'read', 'vote']
    }
}
```
I never uploaded it because as you can see, it has sensitive information. To get your own keys, head over to [reddit](https://reddit.com), create your account, and go to the apps section of preferences to register your app and get your credentials.

Hope you found this useful.

**Comment by mustafademiray** [comment]
i tried this-kinda file but didnt work for me. i tought it was because snoocore is deprecated, but i'll try to fix with this. 
thank you.
